language: elixir
elixir:
    - 1.2
otp_release:
    - 18.2
sudo: false
addons:
    postgresql: '9.4' # Use postgres 9.4
    before_script:
      # Create the test database
      # - psql -c 'create database peepchat_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: rwTPXxyuphHWPFcZEWAkC+0cL33RWZ+VkbVDkX6X4K+KiaEkcHzZVZeFl9c6IBS6KAn4kGAMaoJ7MuTGDo53B8gBUOWh7dy8PP/Xi8iaVtbtEeqbSB6Kpz1XXHkGXz8ukKj7xFwNYJH4hEjfmgm0Zonxx5HyPFfECvrSVdJw4Bvcqjnnv9yPswO4lho9tE489m8XJApYBsqXVdl+d0yZyr43MtlCCt9+LUJPKSS70lgqmPdb0tWScRgvl8hD6W+QgdRNk/zCSg28eH1FwShCBITZaeiZNq0AQGHpInP5/OvmtHdlmrO1jYFY5D+KiJ+CtGP2xxkyMkb7ESMpI4xCAtM8ccmW0NrHOf+iNinrjn2OnX7gFrIvvbN0yajFGFWb+9aBEns5W7YhEN+K8LQ2JpB4gisYpiMCQsER7OYqMoQWmpfPrvBXbiX56+lM5I+z+GKyd7qM8C+FEStiy90zUNjXI22iGho6xxHyFNNFa0lqU3Sc5PwKSpzYIFhcZGoTmorPE7HalZ1bgoOK/ZuNfJy5jMWX2hGv0SRQ/Ufst4d7ZQxkwma2kBaUUOANQds0Sl0KDjHCB8WBIYNvQs0W1ZPKKdCnGP6BMp4l19swh6h6ga0zDDpNVx0BssHjXcRbd7cxamohXKB5TZO8SnbYmcDAF67XM2M+2Fn1EeDzKlU=
  app: fierce-scrubland-40810
  on:
    repo: FrancoB411/api
